### ISSUE TITLE
rustworkx support?

### ISSUE THREAD

**Issue by wshanks** [conda-forge/retworkx-feedstock#6]
### Comment:

In version 0.12, retworkx was renamed rustworkx (see [here](https://qiskit.org/documentation/rustworkx/release_notes.html#relnotes-0-12-0)). What is the best way to handle that in conda-forge? Just make a new feedstock? Or some kind of alias package like described in https://github.com/conda-forge/pytables-feedstock/issues/54?

**Comment by BastianZim** [comment]
Yes, the best way is probably to create a new feedstock and we archive this one.
